course-work/databank/config/routes.rb
Rails.application.routes.draw do
  resources :indicator_values

  resources :indicators

  resources :countries

end

course-work/databank/app/models/country.rb
class Country < ActiveRecord::Base
  has_many :indicator_values
end

course-work/databank/app/models/indicator.rb
class Indicator < ActiveRecord::Base
  has_many :indicator_values
end

course-work/databank/app/models/indicator_relation.rb
class IndicatorRelation < ActiveRecord::Base
end

course-work/databank/app/models/indicator_value.rb
class IndicatorValue < ActiveRecord::Base
  belongs_to :country
  belongs_to :indicator
	def self.select_multiple(cid, iid, year, limit)
		self.limit(limit).where(country_id: cid).where(indicator_id: iid)
	end
end

course-work/databank/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

course-work/databank/app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :code)
    end
end

course-work/databank/app/controllers/indicator_values_controller.rb
class IndicatorValuesController < ApplicationController
  before_action :set_indicator_value, only: [:show, :edit, :update, :destroy]

  # GET /indicator_values
  # GET /indicator_values.json
  def index
		if params[:limit] == nil
    @indicator_values = IndicatorValue.limit(default_limit)
		else
		cid = params[:cid]
		iid = params[:iid]
		limit = params[:limit]
		year = params[:yid]
		puts "special"
		@indicator_values = IndicatorValue.select_multiple(cid, iid, year, limit)
		end
  end

  # GET /indicator_values/1
  # GET /indicator_values/1.json
  def show
  end

  # GET /indicator_values/new
  def new
    @indicator_value = IndicatorValue.new
  end

  # GET /indicator_values/1/edit
  def edit
  end

  # POST /indicator_values
  # POST /indicator_values.json
  def create
    @indicator_value = IndicatorValue.new(indicator_value_params)

    respond_to do |format|
      if @indicator_value.save
        format.html { redirect_to @indicator_value, notice: 'Indicator value was successfully created.' }
        format.json { render :show, status: :created, location: @indicator_value }
      else
        format.html { render :new }
        format.json { render json: @indicator_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicator_values/1
  # PATCH/PUT /indicator_values/1.json
  def update
    respond_to do |format|
      if @indicator_value.update(indicator_value_params)
        format.html { redirect_to @indicator_value, notice: 'Indicator value was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicator_value }
      else
        format.html { render :edit }
        format.json { render json: @indicator_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicator_values/1
  # DELETE /indicator_values/1.json
  def destroy
    @indicator_value.destroy
    respond_to do |format|
      format.html { redirect_to indicator_values_url, notice: 'Indicator value was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicator_value
      @indicator_value = IndicatorValue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicator_value_params
      params.require(:indicator_value).permit(:country_id, :indicator_id, :value, :measure_datetime)
    end
		
		def default_limit
			20
		end
end

course-work/databank/app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  before_action :set_indicator, only: [:show, :edit, :update, :destroy]

  # GET /indicators
  # GET /indicators.json
  def index
    @indicators = Indicator.all
  end

  # GET /indicators/1
  # GET /indicators/1.json
  def show
  end

  # GET /indicators/new
  def new
    @indicator = Indicator.new
  end

  # GET /indicators/1/edit
  def edit
  end

  # POST /indicators
  # POST /indicators.json
  def create
    @indicator = Indicator.new(indicator_params)

    respond_to do |format|
      if @indicator.save
        format.html { redirect_to @indicator, notice: 'Indicator was successfully created.' }
        format.json { render :show, status: :created, location: @indicator }
      else
        format.html { render :new }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicators/1
  # PATCH/PUT /indicators/1.json
  def update
    respond_to do |format|
      if @indicator.update(indicator_params)
        format.html { redirect_to @indicator, notice: 'Indicator was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicator }
      else
        format.html { render :edit }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1
  # DELETE /indicators/1.json
  def destroy
    @indicator.destroy
    respond_to do |format|
      format.html { redirect_to indicators_url, notice: 'Indicator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicator
      @indicator = Indicator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicator_params
      params.require(:indicator).permit(:name, :code)
    end
end

course-work/databank/app/helpers/application_helper.rb
module ApplicationHelper
end

course-work/databank/app/helpers/countries_helper.rb
module CountriesHelper
end

course-work/databank/app/helpers/indicator_values_helper.rb
module IndicatorValuesHelper
end

course-work/databank/app/helpers/indicators_helper.rb
module IndicatorsHelper
end

course-work/databank/app/views/countries/_form.html.erb
<%= form_for @country, :html => { :class => "form-horizontal country" } do |f| %>

    <% if @country.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @country.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@country[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'form-control' %>
    </div>
    <%= error_span(@country[:code]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            countries_path, :class => 'btn btn-default' %>

<% end %>

course-work/databank/app/views/countries/edit.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

course-work/databank/app/views/countries/index.html.erb
<%- model_class = Country -%>
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= link_to t('.new', :default => t("helpers.links.new")),
            new_country_path,
            :class => 'btn btn-primary' %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= link_to country.id, country_path(country) %></td>
        <td><%= country.name %></td>
        <td><%= country.code %></td>
        <td><%=l country.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_country_path(country), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      country_path(country),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_country_path,
            :class => 'btn btn-primary' %>
        </div>
        <div class="col-lg-3 fixed">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
          </div><!--/.well -->
        </div><!--/span-->

course-work/databank/app/views/countries/new.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

course-work/databank/app/views/countries/show.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @country.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @country.code %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              countries_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_country_path(@country), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              country_path(@country),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

course-work/databank/app/views/indicator_values/_form.html.erb
<%= form_for @indicator_value, :html => { :class => "form-horizontal indicator_value" } do |f| %>

    <% if @indicator_value.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@indicator_value.errors.count, "error") %> prohibited this indicator_value from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @indicator_value.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :country_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country_id, :class => 'form-control' %>
    </div>
    <%= error_span(@indicator_value[:country_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :indicator_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :indicator_id, :class => 'form-control' %>
    </div>
    <%= error_span(@indicator_value[:indicator_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :value, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :value, :class => 'form-control' %>
    </div>
    <%= error_span(@indicator_value[:value]) %>
  </div>
  <div class="control-group">
    <%= f.label :measure_datetime, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :measure_datetime, :class => 'form-control' %>
    </div>
    <%= error_span(@indicator_value[:measure_datetime]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            indicator_values_path, :class => 'btn btn-default' %>

<% end %>

course-work/databank/app/views/indicator_values/edit.html.erb
<%- model_class = IndicatorValue -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

course-work/databank/app/views/indicator_values/index.html.erb
<style>
/*
 * Base structure
  */

/* Move down content because we have a fixed navbar that is 50px tall */


	/*
	 * Global add-ons
	  */

	.sub-header {
		  padding-bottom: 10px;
			  border-bottom: 1px solid #eee;
	}

	/*
	 * Top navigation
	  * Hide default border to remove 1px line.
		 */
	.navbar-fixed-top {
		  border: 0;
	}

	/*
	 * Sidebar
	  */

	/* Hide for mobile, show later */
		.sidebar {
			  display: none;
		}
		@media (min-width: 768px) {
			  .sidebar {
					    position: fixed;
							top: 0px;
									    bottom: 0;
											    right: 0;
													    z-index: 1000;
															    display: block;
																	    padding: 20px;
																			    overflow-x: hidden;
																					    overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
																							    background-color: #f5f5f5;
																									    border-right: 1px solid #eee;
																											  }
		}

		/* Sidebar navigation */
		.nav-sidebar {
			  margin-right: -21px; /* 20px padding + 1px border */
				  margin-bottom: 20px;
					  margin-left: -20px;
		}
		.nav-sidebar > li > a {
			  padding-right: 20px;
				  padding-left: 20px;
		}
		.nav-sidebar > .active > a,
		.nav-sidebar > .active > a:hover,
		.nav-sidebar > .active > a:focus {
			  color: #fff;
				  background-color: #428bca;
		}


		/*
		 * Main content
		  */

		.main {
			  padding: 20px;
		}
		@media (min-width: 768px) {
			  .main {
					    padding-right: 40px;
							    padding-left: 40px;
									  }
		}
		.main .page-header {
			  margin-top: 0;
		}


		/*
		 * Placeholder dashboard ideas
		  */

		.placeholders {
			  margin-bottom: 30px;
				  text-align: center;
		}
		.placeholders h4 {
			  margin-bottom: 0;
		}
		.placeholder {
			  margin-bottom: 20px;
		}
		.placeholder img {
			  display: inline-block;
				  border-radius: 50%;
		}
		select, input { width: 90%;}
</style>
<%- model_class = IndicatorValue -%>
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= link_to t('.new', :default => t("helpers.links.new")),
            new_country_path,
            :class => 'btn btn-primary' %>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:country_id) %></th>
      <th><%= model_class.human_attribute_name(:indicator_id) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:measure_datetime) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @indicator_values.each do |indicator_value| %>
      <tr>
        <td><%= link_to indicator_value.id, indicator_value_path(indicator_value) %></td>
        <td><%= indicator_value.country.name %></td>
        <td><%= indicator_value.indicator.name %></td>
        <td><%= indicator_value.value %></td>
        <td><%= indicator_value.measure_datetime %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_indicator_value_path(indicator_value), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      indicator_value_path(indicator_value),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_indicator_value_path,
						:class => 'btn btn-primary' %>
			        </div>
        <div class="col-lg-3 sidebar">
					<div class="well sidebar-nav nav nav-sidebar ">
						<form>
            						<h3>Special params</h3>
						<h4>Country</h4>
						<select multiple name="cid[]">
							<% cida = 0 %>
							<% Country.all.each do |c| %>
								<option value="<%= c.id %>" <%= "selected" if cida == 0 && cida+=1 %>><%= c.name %></option>
							<% end %>
						</select>
						<% select_tag :country_id, Country.all.map{ |c| [c.name, "#{c.id}" ]}, :multiple => true%>
						<h4>Year</h4>
						<select name="yid[]" multiple>
							<% cida = 0 %>
							<%= 1960.upto (Time.now.year) do |i| %>
								<option value="<%= i %>" <%= "selected" if cida == 0 && cida+=1 %>><%= i %></option>
							<% end %>
						</select>
								

						<h4>Indicator name</h4>

						<select multiple name="iid[]" style="max-width:100%;">
							<% Indicator.all.each do |indicator| %>
								<% cida = 0 %>
							 <option value="<%= indicator.id %>" <%= "selected" if cida == 0 && cida+=1 %> > <%= indicator.name %></option>
						 <% end %>	 
						</select>	
	
						<h4>Limit</h4>
						<input name="limit" value="<%= params[:limit]?params[:limit]:20 %>"/>
						<br/><br/>
						<input type="submit" value="Find" class="btn btn-default"/>
					</form>
			</div></div>

course-work/databank/app/views/indicator_values/new.html.erb
<%- model_class = IndicatorValue -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

course-work/databank/app/views/indicator_values/show.html.erb
<%- model_class = IndicatorValue -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:country_id) %>:</strong></dt>
  <dd><%= @indicator_value.country_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:indicator_id) %>:</strong></dt>
  <dd><%= @indicator_value.indicator_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @indicator_value.value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:measure_datetime) %>:</strong></dt>
  <dd><%= @indicator_value.measure_datetime %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              indicator_values_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_indicator_value_path(@indicator_value), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              indicator_value_path(@indicator_value),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

course-work/databank/app/views/indicators/_form.html.erb
<%= form_for @indicator, :html => { :class => "form-horizontal indicator" } do |f| %>

    <% if @indicator.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@indicator.errors.count, "error") %> prohibited this indicator from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @indicator.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@indicator[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'form-control' %>
    </div>
    <%= error_span(@indicator[:code]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            indicators_path, :class => 'btn btn-default' %>

<% end %>

course-work/databank/app/views/indicators/edit.html.erb
<%- model_class = Indicator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

course-work/databank/app/views/indicators/index.html.erb
<%- model_class = Indicator -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @indicators.each do |indicator| %>
      <tr>
        <td><%= link_to indicator.id, indicator_path(indicator) %></td>
        <td><%= indicator.name %></td>
        <td><%= indicator.code %></td>
        <td><%=l indicator.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_indicator_path(indicator), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      indicator_path(indicator),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_indicator_path,
            :class => 'btn btn-primary' %>

course-work/databank/app/views/indicators/new.html.erb
<%- model_class = Indicator -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

course-work/databank/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Databank" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Databank</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
              <li><%= link_to "Countries", countries_path  %></li>
              <li><%= link_to "Indicator", indicators_path  %></li>
              <li><%= link_to "Indicators and value", indicator_values_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
				<%= yield %>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>